version: '3'
services:
  web:
    container_name: ${WEB_CONTAINER_NAME}
    build: ./docker/php-apache-composer-node/
    volumes:
      - ./workspace/:/var/www/html/
    ports:
      - 80:80
      - 443:443
      - 9000:9000
    networks:
      - www
  database:
    container_name: ${DB_CONTAINER_NAME}
    build: ./docker/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - storage:/var/lib/mysql/
    networks:
      - www
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - web
  dbms:
    container_name: ${DBMS_CONTAINER_NAME}
    build: ./docker/phpmyadmin
    depends_on:
      - web
      - database
    restart: always
    ports:
      - 3307:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - www
volumes:
  storage:
networks:
  www:
